export const PAYLOAD_RULE_PROTOCOL_OPTIONS: Array<{ value: string; label: string }> = [
  { value: '', label: '全部平台' },
  { value: 'codex', label: 'Codex' },
  { value: 'sub2api', label: 'Sub2API' },
  { value: 'new-api', label: 'New API' },
  { value: 'one-api', label: 'One API' },
  { value: 'cliproxyapi', label: 'CLIProxyAPI' },
  { value: 'openai', label: 'OpenAI' },
  { value: 'claude', label: 'Claude' },
  { value: 'gemini', label: 'Gemini' },
  { value: 'gemini-cli', label: 'Gemini CLI' },
  { value: 'antigravity', label: 'Antigravity' },
  { value: 'anyrouter', label: 'AnyRouter' },
  { value: 'done-hub', label: 'Done Hub' },
  { value: 'one-hub', label: 'One Hub' },
  { value: 'veloera', label: 'Veloera' },
];
